### ISSUE TITLE
Various bug

### ISSUE THREAD

**Issue by tigerjack** [avian2/noscript#11]
I have several bugs with the newest version of Noscript.
1. Sometime I can't even click the links displayed in a google search until I disable Noscript
2. When I disabled Noscript, all my previous saved settings where lost (things like allowed/blocked sites and so on)
3. On some sites, even if I temporarily allow all the scripts, the site is still unusable until I disable Noscript (check blablacar f.e.)

**Comment by avian2** [comment]
Please ask this on the forum at http://noscript.net

This repository only provides development history for convenience of people wanting to inspect or fork NoScript. It is not affiliated with upstream developers in any way and it is very unlikely anyone working on NoScript will see your question.
