### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by yungtravla** [avian2/noscript#15]
Hi, thanks for the great browser extension.

I would love to get involved with the code but don't have time yet, so I will post my ideas here for now:

Add the following:
  - Allow scripts from **this host** for **this tab**

Change the following:
I find :no_entry_sign: and :exclamation: signs a bit confusing, could we just have :x: and :heavy_check_mark: symbols?

**Comment by avian2** [comment]
Please ask this on the forum at http://noscript.net

This repository only provides development history for convenience of people wanting to inspect or fork NoScript. It is not affiliated with upstream developers in any way and it is very unlikely anyone working on NoScript will see your question.
