### ISSUE TITLE
Feature request: be able to look at the scripts that were blocked without running them

### ISSUE THREAD

**Issue by snakecharmer1024** [avian2/noscript#5]
Title says it all. 

Thanks for all the great work you guys have done.

**Comment by avian2** [comment]
Please send this feature request to NoScript developers at http://noscript.net.

This repository only provides development history for convenience of people wanting to inspect or fork NoScript. It is not affiliated with upstream developers in any way and it is very unlikely anyone working on NoScript will see your ticket.
