### ISSUE TITLE
Whitelist local domain

### ISSUE THREAD

**Issue by MichaelMackus** [avian2/noscript#8]
Is there any way to whitelist a domain like "*.local"? "http://*.local:0" doesn't seem to work.

I'm just trying to whitelist all *.local domains.

**Comment by avian2** [comment]
Please ask this on the forum at http://noscript.net

This repository only provides development history for convenience of people wanting to inspect or fork NoScript. It is not affiliated with upstream developers in any way and it is very unlikely anyone working on NoScript will see your question.
